### ISSUE TITLE
Feature request : Custom PSSH (same license)

### ISSUE THREAD

**Issue by TheAntinormal** [FoxRefire/wvg#10]
Hello,

Thank you for your hard work on this project! This tool is helping me greatly and I'm sure it helps lots of other people too! ^^

I was wondering, would it be possible to add a way to "ungrey" the PSSH placeholder and add a way to enter custom PSSH?

As of now, you need to visit each video's page to have the PSSH detected and you can select another PSSH but only from those already detected (it seems), so if you got your own list of PSSH for a website, it won't be usable and you'll have to manually visit each video's page to detect the PSSH and decrypt :/ 

Anyways, that was just a little thought, I don't think it'd be too hard to implement so thought I'd ask ^^

Thank you!!

Note : I've made another issue with my other account but it doesn't seem to be visible smh, so I'm making one with my main hoping this one will be.. :X

**Comment by FoxRefire** [comment]
Since this project is being developed with an emphasis on retrieving the key for the video currently on the page, as I will not be implementing this functionality officially, but you can do so yourself by simply removing the "disabled" attribute from the PSSH input field in popup.html. 
```diff
<form id="wvForm">
<label for="pssh">PSSH</label>
- <input type="text" id="pssh" disabled/>
+ <input type="text" id="pssh" />
<input type="hidden" id="psshIndex" />
<input type="button" id="psshButton" value="Select" /><br>
```
