### ISSUE TITLE
[Bug] corsFetch doesn't work correctry on chromium-based browsers

### ISSUE THREAD

**Issue by FoxRefire** [FoxRefire/wvg#11]
### [Describe of bug]
When using a scheme that uses corsFetch with a Chromium-based browser, the content script does not make the request successfully and fails to retrieve the key.
Debugging symbols are output, so it appears that popup to content message transmission is taking place.
This is probably caused by differences in the way asynchronous processing is handled in the Chromium-based browser compared to Firefox.

### [Temporary solution]
When using schemes that use corsFetch(Amazon, Comcast, RedBee, and Youku), **use Firefox instead** of a Chromium-based browser

### [Background]
Some license servers often require that the original Origin header be retained when sending requests.
However, CORS, a browser security feature, prevents this from being retained if the request is sent directly from a pop-up script.
To work around this problem, a corrsFetch() method is needed to send the request through the content script.

**Comment by FoxRefire** [comment]
Perhaps this is a bug on the Chromium side.
If so, I'll have to report it to Crbug...

**Comment by marioeivissa** [comment]
use firefox work perfect
