### ISSUE TITLE
All times getting same error

### ISSUE THREAD

**Issue by alpgulmez** [FoxRefire/wvg#16]
![image](https://github.com/FoxRefire/wvg/assets/65984122/14055c69-2eb8-48fc-a277-1defc108f188)

Hello, i installed it new. When i wrok this program its getting same keys for all websitesi. i disabled tampermonkey but it didnt work. Do u know how can i fix it ?

**Comment by TheAntinormal** [comment]
"No such device file, read the fucking manual"

I'd say it has to do with your wvd file (but I'm no pro so wait for admin) ^^"

**Comment by alpgulmez** [comment]
> "No such device file, read the fucking manual"
> 
> I'd say it has to do with your wvd file (but I'm no pro so wait for admin) ^^"

do u know how can i check this

**Comment by FoxRefire** [comment]
https://github.com/FoxRefire/wvg/wiki/Troubleshooting-FAQ#i-got-n0suchd3v1c3f113r3adth3fuck1ngma2ua1

https://github.com/FoxRefire/wvg/wiki/Getting-started#pre-setup

https://github.com/FoxRefire/wvg/wiki/How-to-dump-CDM-key-pair

**Comment by alpgulmez** [comment]
> https://github.com/FoxRefire/wvg/wiki/Troubleshooting-FAQ#i-got-n0suchd3v1c3f113r3adth3fuck1ngma2ua1
> 
> https://github.com/FoxRefire/wvg/wiki/Getting-started#pre-setup
> 
> https://github.com/FoxRefire/wvg/wiki/How-to-dump-CDM-key-pair

![image](https://github.com/FoxRefire/wvg/assets/65984122/87033a8b-0adf-4ec8-87b9-b6730dec42f0)
its just for android ? i dont have job with android

**Comment by FoxRefire** [comment]
You can dump CDM from AVD as well, although it will not work at some sites.
And you can also find them already dumped in a Google search.
To comply with copyright laws and to prevent takedowns of this repository, I cannot give you the dumped CDM directly from me.

**Comment by alpgulmez** [comment]
> You can dump CDM from AVD as well, although it will not work at some sites. And you can also find them already dumped in a Google search. To comply with copyright laws and to prevent takedowns of this repository, I cannot give you the dumped CDM directly from me.

![image](https://github.com/FoxRefire/wvg/assets/65984122/813f9025-ccc3-4ce1-9a9d-1b7a65c9eb63)
Which one happened false ? ( system cant finding target file)

**Comment by FoxRefire** [comment]
Use this instead of released one
https://github.com/hyugogirubato/KeyDive/archive/refs/heads/main.zip

**Comment by alpgulmez** [comment]
> Use this instead of released one https://github.com/hyugogirubato/KeyDive/archive/refs/heads/main.zip

same error

**Comment by FoxRefire** [comment]
Then the AndroidSDK path looks not be set.
https://www.dev2qa.com/how-to-set-android-sdk-path-in-windows-and-mac/

**Comment by alpgulmez** [comment]
> Then the AndroidSDK path looks not be set. https://www.dev2qa.com/how-to-set-android-sdk-path-in-windows-and-mac/

![image](https://github.com/FoxRefire/wvg/assets/65984122/705b0ee0-c4e6-4278-8f26-e2e89a756d27)
i installed now but not working keydive same error

**Comment by FoxRefire** [comment]
Could you try this?
https://github.com/lollolong/dumper

**Comment by alpgulmez** [comment]
> Could you try this? https://github.com/lollolong/dumper

![image](https://github.com/FoxRefire/wvg/assets/65984122/f6314291-81af-4653-a255-60b7e2e40837)
Yea its worked

**Comment by alpgulmez** [comment]
![image](https://github.com/FoxRefire/wvg/assets/65984122/439c18c6-edf1-4d55-957d-4991ae8b0720)
but i cant see cdm

**Comment by FoxRefire** [comment]
```
Ready to use CDMs available here!
```
Google search this strings, you will find pre-dumped CDMs that someone shared

**Comment by alpgulmez** [comment]
Yes now its worked why it was very easy ahah
