### ISSUE TITLE
npostart support json decode

### ISSUE THREAD

**Issue by erikk333** [FoxRefire/wvg#18]
Please support npostart.nl.  Is region locked to the netherlands. has free content like https://npo.nl/start/serie/nos-journaal-20-00-uur/seizoen-59/nos-journaal_93615/afspelen
![afbeelding](https://github.com/FoxRefire/wvg/assets/147526653/19fd9466-db1b-4cfb-9e4c-dce3dae12d1d)

Other sites works very good, but this site isnt  working. If it would be possible i would appreciate. Thanks for this awesome addon

**Comment by FoxRefire** [comment]
https://github.com/FoxRefire/wvg/wiki/How-to-request-custom-license-scheme

**Comment by FoxRefire** [comment]
Works on my side
