### ISSUE TITLE
server.yml with public IP

### ISSUE THREAD

**Issue by XtreamCP** [FoxRefire/wvg#29]
Ok, actually I solved it and it was quite simple but . for those who need it can just type in the terminal pywidevine serve --help and you will have the necessary commands

But now we have another interesting problem and I don't know what causes it.

So with your server API it works perfectly on any platform I tried https://cdrm-xxxxxxx.com/devine

With my server it works but not with all the platforms I have tried and on one platform it gives me this error sch3m3n0t6upp0rt:y0ucanr3qu3st0rsu6mit

so at first glance you would say it would be from the wrong schema but in exactly the same execution mode with your server API it throws me the keys and the schema is fine, but with my server API it gives me the error

I also tried directly with device.wvd and got the same error
mention that CDM is obtained from a physical device

So what could be the problem?

1) My CDM is not good for the platform I want to generate the keys from
2) I saw that your API server uses SSL certificate so https, I don't and I have direct IP address
3) Is there another configuration in addition to the one I already made for the CDM Remote API

Can you please tell me if you have encountered such a situation before?

**Comment by FoxRefire** [comment]
```shell
pywidevine serve --help
```
