### ISSUE TITLE
cda.pl guess dont work (DRMToday)

### ISSUE THREAD

**Issue by Psycho-Fan** [FoxRefire/wvg#30]
![image](https://github.com/FoxRefire/wvg/assets/90871967/ef88a2d8-a201-4757-94ce-818e1e6cea95)

Its only bugs on tv idk why

**Comment by Psycho-Fan** [comment]
i forgot to add this error:

Uncaught (in promise) PythonError: Traceback (most recent call last): File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async await CodeRunner( File "/lib/python311.zip/_pyodide/_base.py", line 395, in run_async await coroutine File "<exec>", line 94, in <module> File "/lib/python311.zip/pyodide/http.py", line 203, in json return json.loads(await self.string(), **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python311.zip/json/__init__.py", line 346, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python311.zip/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/lib/python311.zip/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by papa0112** [comment]
![Scheme](https://github.com/FoxRefire/wvg/assets/135028608/8322ba43-8701-4839-892f-b25653d93242)

**Comment by FoxRefire** [comment]
Does the non-stagging `lic.drmtoday.com/license-proxy-widevine/cenc` always return RAW format license?
Or does it also return B64+JSON wrapped license depending on the conditions?

**Comment by papa0112** [comment]
![CDA lic](https://github.com/FoxRefire/wvg/assets/135028608/c938ef03-10ed-4799-a092-772de076771d)
