### ISSUE TITLE
Dumping from avd

### ISSUE THREAD

**Issue by Worz01** [FoxRefire/wvg#34]
Theres a third WVD created alongside the .bin & .pem files - google_sdk_gphone64_x86_64_xxxx_xxxxxxxxx_xxxxx_l3.wvd

Initially I thought it was a cdm `device.wvd`, but I think its not the case as it doesnt decrypt anything.

So, what is this file and is it necessary that I keep it, or can it be deleted?

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by FoxRefire** [comment]
> Theres a third WVD created alongside the .bin & .pem files - google_sdk_gphone64_x86_64_xxxx_xxxxxxxxx_xxxxx_l3.wvd
> 
> Initially I thought it was a cdm `device.wvd`, but I think its not the case as it doesnt decrypt anything.
> 
> So, what is this file and is it necessary that I keep it, or can it be deleted?

Rename *****.wvd to device.wvd and copy it to extension directory, or just copy two `client_id.bin` & `private_key.pem` files.
