### ISSUE TITLE
could be possible to add scheme of skyshowtime ?

### ISSUE THREAD

**Issue by libero08** [FoxRefire/wvg#40]
I open as issue , because i dont get answer in forum:
could be possible to add scheme of skyshowtime europe .
i own account , and i can provide all you need.for do that.

**Comment by FoxRefire** [comment]
I have checked the HAR file of this license server that I previously received from the form and it is CommonWV(raw format challenge/license).

First, add the license server URL pattern to [blockRules.conf](https://github.com/FoxRefire/wvg/blob/next/blockRules.conf) and see if it works with license blocking enabled(**Right-click menu --> Enable License Blocking**).
When license blocking is enabled, video playback should be temporarily fail, which is normal.
This blocks requests to the license server, thus preventing bearer tokens from being consumed.
Please report back if this works correctly.

If not, please check if your Android device can play content **from a web browser (not from native app)**.
If that did not work either, it is likely that the license server is blocking the particular platform, making it difficult to fix.

**Comment by libero08** [comment]
After enable license blocking, video playback stops. then after i refresh page i get this :
![sso](https://github.com/user-attachments/assets/c64247fa-c5ad-4ef4-9dae-4414452405aa)

**Comment by FoxRefire** [comment]
Describe the response body of the failed license request from Network tab of Devtool.

And can you play videos from this site from the web browser(not from app) of your Android device?
If this is not done, it will probably be difficult to correct.

**Comment by libero08** [comment]
error on netwoirkpage when asking for guess keys with extension>

{errorCode: "OVP_00306", description: "Security failure"}
description
: 
"Security failure"
errorCode
: 
"OVP_00306"
If i want to play from webpage of ndroid chrome, return me a message for invite to use apk.

![sso](https://github.com/user-attachments/assets/e40edf39-9eb5-4b5b-9d3d-5ae4388ae08b)

**Comment by FoxRefire** [comment]
> If i want to play from webpage of ndroid chrome, return me a message for invite to use apk.

Does this fail as well as if you load the page in desktop mode?
If you cannot play the video from your web browser of your phone, it is impossible to fixes the issue.

**Comment by FoxRefire** [comment]
Squashed with #44
