### ISSUE TITLE
It is possible to add scheme of AstroGO?

### ISSUE THREAD

**Issue by BudakDesa** [FoxRefire/wvg#42]
I open as issue , because I can't request via form
Would it possible to add scheme of AstroGO-Malaysia?
I own account and I can provide all related info that you need for.

**Comment by FoxRefire** [comment]
Requests to add new license servers are not being accepted at this time due to the large amount of effort involved in checking the operation.

It is very easy to create this yourself, with a few exceptions, such as license servers that verify token integrity.
