### ISSUE TITLE
Can't get a key from Stan.com.au, no errors show up, nothing

### ISSUE THREAD

**Issue by thehiss-guy** [FoxRefire/wvg#45]
Can't get a key from Stan, no errors show up, nothing, the ring just keeps looping

AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABISECRFyXHJa0I/hOHTmjBXVOo=

https://lic.drmtoday.com/license-proxy-widevine/cenc/

Tried in Opera and Firefox, tried including https://lic.drmtoday.com/license-proxy-widevine/cenc/ in blockRules and enabling License Request Blocking - same thing.

**Comment by LucretiaAudrey** [comment]
[request.txt](https://github.com/user-attachments/files/16443387/request.txt)

Dropping CURL request contents

**Comment by thehiss-guy** [comment]
[request.txt](https://github.com/user-attachments/files/16443404/request.txt)
CURL request
