### ISSUE TITLE
DRMToday.js cannot requst ?!

### ISSUE THREAD

**Issue by senkron24** [FoxRefire/wvg#5]
samthing not understand DRMToday.js cannot be request 

with CommonWV.js working evrething fine 

mybe same bugs on drmtoday ?

**Comment by FoxRefire** [comment]
Ah yeah, but I will not fix this for legacy version.
For NextGen version, I will add DRMToday scheme later.

New version beta testing:
https://github.com/FoxRefire/wvg/tree/next
After beta testing is done, I will not actively maintain legacy version.
