### ISSUE TITLE
Spotify now not working.

### ISSUE THREAD

**Issue by ningsibuqu** [FoxRefire/wvg#52]
CommonWV mode was working properly before

![image](https://github.com/user-attachments/assets/5cc480bf-e96f-4f75-b331-84834ddf9b45)
[dlfaanjlapjclccpkcpnlhdofmndbeif-1724334465292.log](https://github.com/user-attachments/files/16711544/dlfaanjlapjclccpkcpnlhdofmndbeif-1724334465292.log)

**Comment by FoxRefire** [comment]
Works on my side

**Comment by ningsibuqu** [comment]
> Works on my side

L3 cdm

all other extensions are disabled and only WVG is enabled

FIREFOX AND CHROME DONT WORK
https://open.spotify.com/track/3U5JVgI2x4rDyHGObzJfNf

**Comment by FoxRefire** [comment]
Issues caused solely by a specific licence server will not be fixed **unless you, the party concerned, investigate the cause yourself and submit a pull request**.
I don't want to spend time on such boring nightmare.
At least on my side it works correctly.
