### ISSUE TITLE
M+ vod doesn't work

### ISSUE THREAD

**Issue by javidial** [FoxRefire/wvg#53]
Hi,
The header that gives m+ spain when playing a video only works that time, so when doing a request, it won't work because the header only works 1 time. Apparently it needs to request the video, get the header and key in the same request. Is this something that can be added in your scripts?
Thank you so much.

**Comment by FoxRefire** [comment]
Try adding the licence server URL pattern to [`blockRules.conf`](https://github.com/FoxRefire/wvg/blob/next/blockRules.conf) and **enable licence blocking** from the right-click menu.
If the cause of the non-working is only the bearer token, this should make it work.

**Comment by FoxRefire** [comment]
Issue is closed due to lack of response.

**Comment by javidial** [comment]
Sorry for the delay. I added the line "wv-ottlic-f3.imagenio.telefonica.net/TFAESP/wvls/contentlicenseservice/v1/licenses" to the blockRules.conf and enabled licence blocking from the right-click menu, but it still gives this error:

sch3m3n0t6upp0rt:y0ucancr3at31ty0u4s31f
[MPD?]
https://github.com/FoxRefire/wvg/wiki/How-to-add-custom-license-scheme-yourself

**Comment by FoxRefire** [comment]
Try a [heuristic scheme](https://github.com/FoxRefire/wvg/commit/c2dfbd5d2f90c01dbc896a52d54d3e082fb4c7a3) that can be used universally.
If this does not work, there is nothing more I can do, as I don't accept requests for particular license server support.
But even in that case, it is possible to try to fix this yourself by editing code.
If you made improvement, consider opening PR.

**Comment by javidial** [comment]
I'll try that. Thanks
