### ISSUE TITLE
check can you fix modules. so that it works with getting keys

### ISSUE THREAD

**Issue by invisiblecoder99** [FoxRefire/wvg#55]
license response 
`{
    "heartBeat": "300",
    "sessionToken": "tez51n8baTeBRpwmlHv4miY8Pu1QhC/R3CAybUe3bvUuqGdpaIdMdTSSpzFJTy875e3uarWBoMh4vyun7GXYXsf7qoBRD7MwP8xCIJY79d6p5YBT9K9XZNqa4XpPB+o0ut2t3+Q+k/ca4zBTMQ83UMarZR0oW6qy7Ww86/5ZdA+1Rq7+5NndqUWu7RfI/iPm/nSCBVtydUB9dXN5SeqQ2qhX71mpiVVwJkwwc84PmtK7/bdPDpAw1mRZPop3K4zrKar1NvI04jzHHvOuoNwqeVBJNiuQw98AAfT11zYRAUo3s0tvwrsW+H4677Ay4ikQm8KDWl1WhGeTew6XqRH/WV9BJ7upJ5zEmuwWiCLuh09KstjRlrxh+7ie5CVbZGukRajUhEyPZkkjubHDv9vKn7F1QZHLvdEXgpjrUeq7SFReexHWG7c3YahgWHWjAtQGKBbKC5qhpAmqemf36+845VHJl5gR+DYAeBve4Ccl5da/7z4bH/O1uxQ9Bj9yJTJi8CA/lDsuabSivWdH41GZjPRg3fwql5K9q5RH9PQGLWv0unQEIkVqZivLcTo5CKu/ZHPzeXCihYBlbXRYaXo200v8dkQfmnGTB8fex2PicvF179hYQHA8ZQMV78i7CD0jdGadxtV1KHYK1l+cBApcCrMdKsui8saQKhknQ4ZVzEXafhFX59Bl0LlAThcD4fp/POSCME9bg4Y=",
    "license": "CAISgQIKNAoQzj87nQ3k/xkTV8bWMS51vhIQzj87nQ3k/xkTV8bWMS51vhoAIAEoADgAQABIvffstgYSEQgBEAAYASCkAzCkAzh4SKwCGlYSECivwGVUKQvKFdg1RCwrBsIaQBRcdJZi6XOWwWaDT3rq7g57YL48XZN1wjl8cDtqvlJbXST3hbDZIKkeYh8+4tF2etwsNqlJ5G5oN5OJiemzE84gARpUChClEJ+j+2lK/oY55Ogx/qL2EhCO3OFjQWQ5qyK/yfGdIfCCGhC+OzFMUyojQTw6mr+DvxxvIAIoATICCAFCEgoQa2MxNgAAAaRlO8X2wAACDGIAIL337LYGOABQBRogJaTFYeBWykQKG6U4cTxS1Gl7ilR9yPNWRmW0cNNA3TMigAHQVK5bLOcVq5+PdQJQ3Mq+E91b3yr5fhR/CsBF0uBJdCDBWE2TpFpXETdPqoQwb6OOaoO9ldOZyamowgHn9VZBU8S58mSc+N1QAs2fe4phIj+Bbw3xm79RRU1tjqkbIJQMbU4pRmyCMdMmhBYoneEwxpzzN1lbMr0uSNm/H43bHTozCjExOS4wLjYgQnVpbHQgb24gQXVnIDEyIDIwMjQgMTY6Mzc6MzIgKDE3MjM1MDU4NTIpQAFKsAEAAAACAAAAsAAFABBlO8X2Sb8bBgAAAE0AAAAQAAAAXwAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAaQAAAAAAAAAAAAAAAAAAAGkAAAAAQAAAKUAAAAQAAAAtwAAABAAAADJAAAAEAAAAAAAAAAAAAAA5QAAABCoLWDjrdYf/qpay1hEV5enYxZ9g5VV8wdnSbQLPa98CVgB"
}`

license request

`fetch("https://apigw.cz.vtv.vodafone.com/vtv/ccursession/v1/start", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9,km;q=0.8",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "sec-ch-ua": "\"Chromium\";v=\"128\", \"Not;A=Brand\";v=\"24\", \"Google Chrome\";v=\"128\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site",
    "vtv-authorization": "HMAC-SHA256:05ef00f0408b08c3a0795546ae9d1de90e148d6b1e3516fec6b9bfb9d2692890",
    "vtv-id": "29968fd9-47ff-4797-bf04-9aed221d4597"
  },
  "referrer": "https://tv.vodafone.cz/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"requests\":[{\"action\":\"checkEntitlement\",\"params\":{},\"body\":{\"assetId\":\"174471574\",\"assetType\":\"epg\",\"contextDataParams\":{\"objectType\":\"KalturaPlaybackContextOptions\",\"assetFileIds\":\"109107195\",\"context\":\"CATCHUP\",\"urlType\":\"DIRECT\",\"adapterData\":{\"manifestStartTime\":{\"objectType\":\"KalturaStringValue\",\"value\":\"2024-09-06T17:00:00Z\"},\"manifestEndTime\":{\"objectType\":\"KalturaStringValue\",\"value\":\"2024-09-06T17:56:00Z\"}}},\"apiVersion\":\"5.3.2\",\"ks\":\"djJ8MzA2MnxkcqD_m05S3zmj-A2kOAq3aL8w3rMBZ5CJm0uyK6TaqJ90KA52A72CkoCSMlJIUl3o3aJTdKF0_m1mA0fMMPMwTi115n-EUbQpGFAGSkg1pUvqSvgCE0KXTbzJWH8Kkk34-YTkL3tdHNNXAojtSgNtRO-854rJfaqvj89PmuRAMtuJIh3LpqsmO4nAJi3KkXffH7eBsc_ye-ehKGlkDQUKc5fesWaB97TltZFHsVVF3t3ss4aCS-W2nAhzmv_u5Mng0A-vWCUqb5RbECuoi-h-BlWYa9fjGeRvAXlHb_v6QkQPFQGCXVOW57iRczIvytZP4m5nWiUpI5jobbx-cAMSKXDeOnhHilNFq3i5nyQ6izI_-JcWaYKR5HZ2dE0erggy30BA9CzSUYuiJ5DzFWO8ZJYZmwPIsWpYA9wgqy7_L4XIL5iOLbtqGYgK6YD2BuTJYJF75tvQe4cBArkebRa9mgH6jbjNBVMaUEkhKSNJNGXIBFbV40o3WX2hvECtCj4A3YugmRXD_1mO6rcFo9xipK2_lliPBCWPVtB0aXRU5N9n1bQFg1xiGPbY0Nc3rzUA_IRj7bM22eXotkqnedFm_vDzaq3lE7tByV9aRBeimvSGNnTnseMayMHrBw2b0voBujarXmeKDY5w5OoRPT48lx6W0lsu_jWVpkxfODOosqHT8r42Lu-78_IFvTedOTtozavKewXkaDO_50pIrsRMqNgFBMsvm3wGU0u2eGMHgg==\"}},{\"action\":\"bookmark\",\"params\":{},\"body\":{\"bookmark\":{\"objectType\":\"KalturaBookmark\",\"id\":\"729140\",\"type\":\"media\",\"programId\":174471574,\"position\":1704,\"playerData\":{\"objectType\":\"KalturaBookmarkPlayerData\",\"fileId\":109107195,\"action\":\"PLAY\"}},\"apiVersion\":\"5.3.2\",\"ks\":\"djJ8MzA2MnxkcqD_m05S3zmj-A2kOAq3aL8w3rMBZ5CJm0uyK6TaqJ90KA52A72CkoCSMlJIUl3o3aJTdKF0_m1mA0fMMPMwTi115n-EUbQpGFAGSkg1pUvqSvgCE0KXTbzJWH8Kkk34-YTkL3tdHNNXAojtSgNtRO-854rJfaqvj89PmuRAMtuJIh3LpqsmO4nAJi3KkXffH7eBsc_ye-ehKGlkDQUKc5fesWaB97TltZFHsVVF3t3ss4aCS-W2nAhzmv_u5Mng0A-vWCUqb5RbECuoi-h-BlWYa9fjGeRvAXlHb_v6QkQPFQGCXVOW57iRczIvytZP4m5nWiUpI5jobbx-cAMSKXDeOnhHilNFq3i5nyQ6izI_-JcWaYKR5HZ2dE0erggy30BA9CzSUYuiJ5DzFWO8ZJYZmwPIsWpYA9wgqy7_L4XIL5iOLbtqGYgK6YD2BuTJYJF75tvQe4cBArkebRa9mgH6jbjNBVMaUEkhKSNJNGXIBFbV40o3WX2hvECtCj4A3YugmRXD_1mO6rcFo9xipK2_lliPBCWPVtB0aXRU5N9n1bQFg1xiGPbY0Nc3rzUA_IRj7bM22eXotkqnedFm_vDzaq3lE7tByV9aRBeimvSGNnTnseMayMHrBw2b0voBujarXmeKDY5w5OoRPT48lx6W0lsu_jWVpkxfODOosqHT8r42Lu-78_IFvTedOTtozavKewXkaDO_50pIrsRMqNgFBMsvm3wGU0u2eGMHgg==\"}},{\"action\":\"session\",\"params\":{},\"body\":{}},{\"action\":\"license\",\"params\":{\"drmId\":\"edef8ba9-79d6-4ace-a3c8-27dcd51d21ed\",\"challenge\":\"CAESpCASMgowChoIARIQpRCfo/tpSv6GOeToMf6i9iIENTA2NhABGhDOPzudDeT/GRNXxtYxLnW+GAEgvffstgYwFjj2i++pBkLQHwoUbGljZW5zZS53aWRldmluZS5jb20SEBcFuRfMEgSGiwYzOi93KowakB0xbdUA99kFdZv4tD9GRuN6YAoS0BcXkA80PZmRP3gwQBnEbT6EaHHt1TzsnMG1mPiinDBrwtgqV16QQdjS6IPtlVNKfmUw7B2e9hnRAEFrJyiKj0W5dnA04emu0OwPNApz6ik57xJiaIGNztAjV3wzXgrk72Tjw2JPjeMTbZmqZICGmI8gkL0YCOuzqgON7HpOPUOGxcENhD0y/tiGkUa9AzWixz6xerl1CseBQxtsWWCDv35yJKXKQJSMXaUqByVvxQeg7xeKzcRkKb4NO4msM5Jr5FP7Uf1ugnwnvkry8D02PYjjSrqxG0vFPrJHdCrqD7tManTHDASybBH7dS/uEIIxmqTZG2UceJTVS8Euy9eFnXOZOZjciMxmG+k6iljBG8W0kJxBpIuxHJdgafgUYt2vXeINUv7PJrBrFfpPF3ByQfTzO1LppoY7bUlM8n0uabsx3C7c2RQ75G2uzeQ4Ug/HuLLrQU7t6VLqzAFU4wD6FdeXwwd4h4ZvGXP/YguDaHXDXEOXZoqUeE/RuuTeKdTozJjfT37Q2k9w7LUfAA0i16NuBGa0O37v42iMLYe5gY3ixno7zdKhdR6rQNkABC8Y4gdQoG4/kOx0D8+yEhCwceRZhdgwifCJ5rZjx7fTEcWDYOavqOiZef2SKQHP5GFxdrzr4rWk3/Ms0MMQP8KZSpxPbbEp5PY20K4dJcuQcY3Y81XKSyxIZTN7dlC1pCFkPJ78T2Gswi+6zrb1KBjaKcQLkKAyRZQSyDxN/uhmSpLJMEJm6Lnk1TCXGfLiv/W2iSnoYzEvO/o9410odcGNGbPXlIEv03E1uDXvjGx8B1RC+/ENseZoe1uTJ4NGfGHIkZMht1SINq11nqRLrfhNKQ1CkmZ7xULlvDxYiLBlnSWYAAxxX5Qzwho/ssNw4U+8GRr2Muu1m81xkT3SelVwY2AiK/DA8dNev2BWlBD69kmSYwX2IRrefYWoGzWoNBeiASBVo4Dr5C0vvjjAQIPbFecdW2YS5G3S9nPjzdKWAEquQWcDq2acv3tGB9eRIwu7mrV9YvQIcGxRnQfvzx6e5dmmeed608pfEuARF5Cq9bV4Ai6KKnAfViNCRS7sO1Qg8kf4uZ0vq2uZasDErI8RJRtivlhieGgZqJRHAPActnCb8MgJtqCHY8iCzzWqyQCorhqrqcr78/6B/2JgsUv+XChlz1Iq6gp+shSZ117H8HtpWRnUc6oCdK5nlM5qDHIa61uN2zpeNXoboU+YIpAODCwwgXSiyjc7q0wvNy6IMc+VFdg1sTYIIpzF/mPxbUl4GcAh3iSjySLLl0pR/0PHWGWBf34ZBiCdzqy2Eky+G2f3QDqUR7gB4SSSUGmJJgiuZkX9V2Tj3VqQiT6POVGQkPX8+WorJEKxgSbh+8BZBPj9RKaK2QOctII1Cl19jvhcPvIdEJJrv5VXoaZrACKn6fYPs7gMnNqOJJLAKOIf47O9yGJHnLrAHWwhBaB4yhvT7aozyV0gJV8eCOTwCCC20w0lBhPnYx2fHaXvh8/QO+KP6c7L/7ZBq2IwA8FzC2MeU0xRvU5z6cNEClgU88yQw/nHT4BYWkG7plv0DNnKquBBcowbaBmyBGCIOgzp1DrgKEH4PNhGQWqQQ1hSZFrxL7t1TqKhSp6Lnsbsv+zWKcrDsuunT0PNGA1F/m/KojQp0mAan5tmIftJvKNdhXFphrFoQLpYGSi6azcFAyPwqQWA9blXw2LVi7XkQWm7PULH1g3wGSqet8S3QAUOV/4yOYJebznpj+i6Z6zTU9Gi0/BekjGO5xqF5yp4XGTpESq4Z8xPZR4YF92bxji7f8YV2+P7Layx6uVc8zQCXdr50RqgPtOuR2VSOSgVG2hNKgg5o1G6/rbXYIXqeEjATLYAKhocsno0ghuQN5+4bVXnzYYfFxL8oogXHEYKCykALN8UDCmnVD0bCdfOwULFal2ef0V4BeJvnpxhhSddc+wYLy0RDWhck9kN/vhrY145S72X6frQA39dd+bMFYGgWSeHyWJGeIhGZfsUPEpeTa+BBl7ii+6KwJIPw3cnZC813jxtkNTkqpFlM5ErbTQk2talT8/hDfoxM8Y2ggWE6194Wtp2IvWru3WNym1hjZBa768/rf1kGnyAqNdaoMLgSWZV3i4x0O+LWAoloL+SDV+rfGWnJG5myXZC6z2beJKX1DX+mBfOkshYSUZxzoa5M9LcU2icZV6+w+x7ubWEN7O3so89QBHpVtZ4oy8HoflzfMRFQXzsO9RrvIbkGT3EaFPZ7uklVRCr1udvNQrIo2dNjCQ679Q3lMog7Tsx/3H4zxqpjiaPFoqQG5pHjrzw6pAgN/U5N9FWHvoZrR5PTfrR32pqrW/duPdvvm1FgC7vfEdQenFez3SoSbAVWIfq9f2s8veUpJOtb0ftECuVJcCdMWKaQnpS2yzy/V98JWdMlbzRE5zsY/60u8+gVJja3fLmk62JoBQazaERdJPP6wD+iJojrUFXer6gvRX/IoOPGgMu1lOz9sPVFa++687Fe5JUopAUHm0IqIEw3eBNPZcQ/emxcHHiSrYG9XrZp7uV7kyYXt3beLc+J6t9fSmlVziYlAZXH8r+xFHIUG8ZPkfM/8l8ExBfpfQ8Fq+1KPfzgvUQKCwdIAoKxMXT/TXFF7fbzQH4UOYcBiwNeuVHi5sSthYWdJJWgIQE1/KsaQ3ISK0WaIXIvzLrj3WVDHNOt+36ngi9oKmPVyOX8kVVQi76YDnKL/1fjtBKr0tBBFLrQ6RLf2T4ZRj0j4PczzQtwCI9so9Rcvgw17iaN96yalUXeVgpDC+SIhZqVkHMQN3rdVUhXo+moi34QI4Cv/4PPr6zIU129/LHAPrQNn5tHnTvlsovSuZ1ClIbp6LNsi+rE8+TUiuNQmmGAVqPu0Gt8PqCMTRvk5izF/KZyO9gm4KJxBsjY6KhBj/3uiPO7bQBmxd3sRUwIduTa85Pu2H8mJV+Cx/W8sEasO/yLJb8bHXHqrQ4IxKDL3GHZchlv3t4QbNVMSGDaNh5zJWDkRpDa25rOHnF+iQOnX5kaHZYCGm3KMK8tK35CUGRJjoE7/PRT0C5PyLLi9gUk/F6NWn9wfbyTsCEX24q1oIINHj1gp15bdrGWUi6MwyxmaAysaBsjO8NE+LBtSh3qH/eFGGacN7H3cM31x9VExyWvgmO8QVWBQWiSK35QRKv6nT9doOd3CegmxFwIFV7Nl+Lq9tfvg32PTFG7Tby9DA37FR1lyb/tfGHMVH2OgcpbJJFFfFbq7yvyKDwm/e7lT5kq4yzIrmkI2cf5sLKQE7wsW4muT6MbwrGvML6xH5VGmRHzwF8VfrK4o+z8bdC6ZdFVfY/BZx6ZcJuAYqERP16ueBZr5aNPdGhozBrVYqMz8Na0bH1O/lUGpsVPX6/aaswX+tfwqtiuKAZaaeJCN21ubNWvbb+dG0e/yRyvNy3mpVFkzmG1e8tPFIuQYZXxygSt5tzJ7nMBXbE2FWq9PsAu+q9VeOgw6nVo2p53gzvV7naq+fLWVkgUG1okoETq69XI4+hC35WpJM+6Bo5onlyJSyYFQlUChLxdEP1sBo6k47TUTe6JOJVIl7Qwi8iXKFkZjGBZsoAKxdpnmxk/iT5mqK/pqxsu6bI/1ZP9Oy/NDQwlpo7n03BFJdaO2TmyvFrBLP2bKqmoqPNbNDAYJIBBH5vKtanhHwYj5g/eqyPB/+hIw5jbnaE0ZgRiHaXudHY62aVyd/hHVlPyVVPIVHrZ/ZaOzU5h6Ze80mSC7LTOZxp0e3UtgHQaA2c7GVrtGO97/MWopqhfyAB+yZi/udiYVeDVRkADvE9LmwCyf7wx+/L7Tqcuc3qOiV3LUJj7r16LizVYVP5LyqXw6EDvNTr9B2tdJRuUGaIDSYHNo9ImAKfJjNgAOXQT5fZGr4rC6nzGEyUE+sOV7EbsB3zanfbywJFzNk8PS+NA4GDLagb8Exyhp6VzqiWhu8nRjJbd6FX7/FDgHh23HR3IN2T9YsvfxnIsJZFo+IL9IH3IePc3EOywQuCB4oS+yW7ktLgpkj+OPxXkvhP8pwD5Mc1PjQcQaNoxMeB8dROVXzlD66V1NKPl6NR+HIXnbE+z3KVkEZ3VBa20ZtAcpMPDh9aH28M9bN91yTZSz1agRdd0pKN+INXYKkdZ1dwP7S8hzhwO/6O8iLwTb4LUIf/Goo1XGk8e0lYl4kjhFLrY7I4nVdLKXaa/i6+nu0bn/rqTSd8+UbqvuEJhL1B8hC9jvmiS8/5sKgiHL3fk6CN6X+qS3cGDe4CE+aK9sSRgrm09RhuZhvJndYGiJolmi3WvO2Gh+vdeY3sxw0a3mlwt/xGjSUfBBK3eUtGIJixTTjs9r1Zy8eRf2p/YtKL6ju0emCd39jHlUqUxy7KF0k/Cf0mClFIo7lzVNkOFmmftrAs/eaqkOmV+WV+v2UqfXELIMwK51Uu3ITxXGLa0CNMhVA8VY8sL8nddtQvgoKOXr44XYj1XmadiWKQQan5EXGTbz1cTR2eGHSS8g3Q66QPkCzHpsUw8yoYN89n0jc7pszNlTqGjfqdgLJep/PPdbkga5AwCC7zlgchjn9OPcCZiAGueZcqisU0z+RMKkIKBHHWNLjNVTJ7nwV+5TN32nKyTFvhWFZPCZZ+xKrB+YWxp14v1MokidRmg9LskxXQddONBuOGBGbGWAWoA/1Y9KWDbkxMKK+C4xRoQTFsODSSTv9nUGmX9U1jKFP90tTevJ72oo9dqQLfxY0J3qlsctxFxOw4vJ19XaK8Lueo+4tk5OZ/LY8bChTyx1il6P+8RUQpMcxIAOmTw6vcv4KEa7VvIPo+X8CbCfm1fqRYYvlYc1Lx/uhJIYN5PJgwysO4kawhqAr6dIpodXYU+g3rgAMZUL8Gixgqx0r25+8qJBu6+oNG37HIF6Mtat/xiXTrZMcMHYIkwbTejJj2ZyIQ1LMfhABev7gPjRURFtsmdSqAAkjXG1OD7hOlXk+SHkI5QUYL/fTBHQYuUjhfUvFKyjEidcYypMXDXlx8weGhkaLyaQ8PbRmVO2RJ6k+sRoInEkMidLSSsqz4hhDnoGPRTMZ9maXI5hdF+NNR6EuIVN7WJKAoKmToky4qKSncZV9hAXMTwi/gH0/Tn9hAXH4SJ+kFzN9/outDwElR0g3C3kFx2dBX/kFJyOGr04gCN32kQGP+M9u9bBNdyAaPRwN3WfpJSnyXzKYC96Fk+8sTb+Qse+5O6YQF0lzyYS2aDjC29kndKPHsWsAJIupMLHVi49AOmVml4phirXwb42VMKEqT+BS974MwnekuRVFPVkPW0uVKCzQuMTAuMjgzMC4wGoABqHrZ6iObOIXctNk0z+0A9iTwOn66qNb2LXF9bB4q1LJeEYk2ze362CEStVrCAB9mITYs96miHVrCLRKY0eDIeS9AtEL+0iHBiyX6DernhYWIeS/Sn7AEt1BBrLo+GP+8Mcz3+6vmO7bTUBanSVyshfxQH4hZSqx4cAvAeHuFsspKFAAAAAEAAAAUAAUAEGU7xfZJvxsG\"},\"body\":{}}],\"apiVersion\":\"5.3.2\",\"ks\":\"djJ8MzA2MnxkcqD_m05S3zmj-A2kOAq3aL8w3rMBZ5CJm0uyK6TaqJ90KA52A72CkoCSMlJIUl3o3aJTdKF0_m1mA0fMMPMwTi115n-EUbQpGFAGSkg1pUvqSvgCE0KXTbzJWH8Kkk34-YTkL3tdHNNXAojtSgNtRO-854rJfaqvj89PmuRAMtuJIh3LpqsmO4nAJi3KkXffH7eBsc_ye-ehKGlkDQUKc5fesWaB97TltZFHsVVF3t3ss4aCS-W2nAhzmv_u5Mng0A-vWCUqb5RbECuoi-h-BlWYa9fjGeRvAXlHb_v6QkQPFQGCXVOW57iRczIvytZP4m5nWiUpI5jobbx-cAMSKXDeOnhHilNFq3i5nyQ6izI_-JcWaYKR5HZ2dE0erggy30BA9CzSUYuiJ5DzFWO8ZJYZmwPIsWpYA9wgqy7_L4XIL5iOLbtqGYgK6YD2BuTJYJF75tvQe4cBArkebRa9mgH6jbjNBVMaUEkhKSNJNGXIBFbV40o3WX2hvECtCj4A3YugmRXD_1mO6rcFo9xipK2_lliPBCWPVtB0aXRU5N9n1bQFg1xiGPbY0Nc3rzUA_IRj7bM22eXotkqnedFm_vDzaq3lE7tByV9aRBeimvSGNnTnseMayMHrBw2b0voBujarXmeKDY5w5OoRPT48lx6W0lsu_jWVpkxfODOosqHT8r42Lu-78_IFvTedOTtozavKewXkaDO_50pIrsRMqNgFBMsvm3wGU0u2eGMHgg==\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});`

module i made 

`import base64
from urllib.parse import parse_qsl, urlencode
import json

# Regular expression pattern to identify the DRM license URL
REGEX = r"https://apigw\.cz\.vtv\.vodafone\.com/vtv/ccursession/v1/start.*"

# Function to extract the challenge from the license request body
def get_challenge(body: str) -> bytes | str:
    # Parsing the JSON body to extract the challenge
    body_json = json.loads(body)
    for request in body_json.get("requests", []):
        if request.get("action") == "license":
            return request["params"]["challenge"]
    raise ValueError("Challenge not found in the request body")

GET_CHALLENGE = get_challenge

# Function to set the challenge back into the license request body
def set_challenge(
    body: str,
    challenge: bytes
) -> str:
    # Parsing the JSON body and updating the challenge
    body_json = json.loads(body)
    for request in body_json.get("requests", []):
        if request.get("action") == "license":
            request["params"]["challenge"] = base64.b64encode(challenge).decode()
            break
    else:
        raise ValueError("License request not found to set challenge")
    
    # Returning the updated body as a JSON string
    return json.dumps(body_json)

SET_CHALLENGE = set_challenge
`

**Comment by FoxRefire** [comment]
Send PR if you made improvement
