### ISSUE TITLE
work alone python script?

### ISSUE THREAD

**Issue by sedansindie05** [FoxRefire/wvg#68]
Hello,
I am very interested in your project.
I am currently researching and want to implement an application using only Python.
For example, I just need to run a Python command like ```python gen.py```, and it can generate a password for me.
I would like to ask if this is feasible?"

Thanks!

**Comment by FoxRefire** [comment]
First, you have to learn how Widevine works, and how this extension aquireing keys.
These informations are described in docs.
If you cannot understand at all, you have to learn networking skill first.

Next, you need to determine how to obtain the URL, headers, request body, and init data that required to aquireing the key.
The extension gets this information by hooking EME and using the webrequest API from webextension MV2, but this is not possible without the browser extension framework, so you will need to consider an alternative way such as calling web API directly or using selenium, pupppeteer.

Once you have decided on the overall specifications of what you want to create, you can break down the process into smaller steps and select the necessary libraries, etc.
If you can't do all this right away, start by understanding the more fundamentals.
