### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by BlenDaniel** [FoxRefire/wvg#7]
Hi,

Thank you for providing this tool! 

It is added to the browser fine and gets the pssa and licence url. But doesn't get the results here. It just doesn't display it. Please can you help? I have pressed many times the guess button.

Where can I find device.wvd?

<img width="779" alt="Screenshot 2024-04-19 at 1 16 59 PM" src="https://github.com/FoxRefire/wvg/assets/38203322/cf9b0781-0ca4-4e4b-b0c7-b01b6b18e195">

**Comment by FoxRefire** [comment]
>Where can I find device.wvd?

Just google it
https://forum.videohelp.com/threads/407466-how-get-wvd#post2671448
